### ISSUE TITLE
make image fails to find the kernel

### ISSUE THREAD

**Issue by mrguitar** [mrguitar/fedora-rpi5-bootc#1]
Deploying container image...done
ERROR Installing to filesystem: Creating ostree deployment: Performing deployment: Deploying tree: Initializing deployment: Failed to find kernel in /usr/lib/modules, /usr/lib/ostree-boot or /boot
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.bootc.install-to-filesystem", line 53, in <module>
    r = main(args["options"], args["inputs"], args["paths"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/osbuild/bin/org.osbuild.bootc.install-to-filesystem", line 48, in main
    subprocess.run(pargs, env=env, check=True)
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bootc', 'install', 'to-filesystem', '--source-imgref', 'containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]35353bfba60ea5cef881c09257d199f4f47b060ab8ff87b4379a14d2494e9665', '--skip-fetch-check', '--generic-image', '--karg', 'rw', '--karg', 'console=tty0', '--karg', 'console=ttyS0', '--target-imgref', 'quay.io/mrguitar/fedora-rpi5-bootc:latest', '/run/osbuild/mounts']' returned non-zero exit status 1.
mount/boot-efi (org.osbuild.fat): umount: /store/tmp/buildroot-tmp-i7baazaq/mounts/boot/efi unmounted
mount/boot (org.osbuild.ext4): umount: /store/tmp/buildroot-tmp-i7baazaq/mounts/boot unmounted
mount/- (org.osbuild.ext4): umount: /store/tmp/buildroot-tmp-i7baazaq/mounts/ unmounted

**Comment by dsedg** [comment]
@mrguitar finally made some time to look at this again. 
I don't think we can get the dwrobel kernel to work as is. https://copr.fedorainfracloud.org/coprs/dwrobel/kernel-rpi/

From my old testing and some discussion on the project it looks like the way the kernel is packed it incompatible with rpm-ostree. 

I can think of 2 ways forward, manual installing the kernel in a post config script when building the image.
https://pagure.io/workstation-ostree-config/tree/main

Or building kernel and packaging it in a way that will work with rpm-ostree. 

going to give building the kernel a try by hacking together the build for the vanilla kernel, dwrobel kernel and the downstream rasberrypi kernel 

https://copr.fedorainfracloud.org/coprs/g/kernel-vanilla/fedora/
https://github.com/raspberrypi/linux
